登録画面のルーティングの不備
f-o-f/open-sample pull request #7
Opened 2022-07-19 04:24 UTC by toyoshima-miyu

createのルーティングができていないと思われます。
ご確認お願いいたします。

2022-07-19 04:50 UTC, f-o-f requested changes
.DS_Storeは環境依存ファイルなので、.gitignoreに.DS_Storeを追加して、コミットに含めないようにしてください。

2022-07-19 04:56 UTC, f-o-f requested changes

2022-07-19 04:56 UTC, f-o-f commented on README.md
> -# open-sample
README.mdの変更は元に戻しておいてください。
また、このREADMEの内容はclientのものかと思いますので、clientフォルダに格納してください。

2022-07-19 04:56 UTC, f-o-f commented on client/src/app/app-routing.module.ts
> +  // { path: '', component: GoodsListComponent },
createの画面が表示されないのは、ここにルーティングが追加されていないからかと思われます。

2022-07-19 04:56 UTC, f-o-f commented on package.json
> +{
このファイルの配置はclientの中が正しいかと思います。
clientとserverでそれぞれ別アプリケーションとしてください。

2022-07-19 06:10 UTC, toyoshima-miyu commented on client/src/app/app-routing.module.ts
> +  // { path: '', component: GoodsListComponent },
goods-module.tsに

const routes: Routes = [
  { 
    path: 'goods', component: GoodsComponent,
    children: [
      { path: '', component: GoodsListComponent },
      { path: ':goodsId', component: GoodsDetailsComponent},
      { path: 'create', component: GoodsCreateComponent }
    ]
  },
];

と記載していますが、そこと連携できていないということでしょうか？
（詳細ページは表示できました）

2022-07-19 10:05 UTC, f-o-f requested changes

2022-07-19 10:05 UTC, f-o-f commented on client/src/app/goods/goods-details/goods-details.component.ts
> +    this.goods = goods[+params.get("goodsId")!]
createの表示については`+params.get("goodsId")!`が正しく制御されずにエラーとなっています。

2022-07-19 10:05 UTC, f-o-f commented on tsconfig.json
> +/* To learn more about this file see: https://angular.io/config/tsconfig. */
この辺の設定ファイルをclientに移動しないと起動できなかったのですが、置き場所合っていますか？

2022-07-20 01:18 UTC, toyoshima-miyu commented on client/src/app/goods/goods-details/goods-details.component.ts
> +    this.goods = goods[+params.get("goodsId")!]
ありがとうございます。解消しました。

2022-07-21 02:56 UTC, closed without merging